import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/theme/globals.scss';
import { DictionaryContextProvider, ThemeContextProvider } from './_shared/context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <DictionaryContextProvider>{children}</DictionaryContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
