import type { Metadata } from 'next';
import {
  DictionaryContextProvider,
  ThemeContextProvider,
  TypographyContext,
  TypographyContextProvider,
} from './_shared/context';

import { sans_serif } from '@/theme/fonts';

import '@/theme/globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TypographyContextProvider>{children}</TypographyContextProvider>
    </html>
  );
}
